rpls_dic = {
	"witnesses":"these dudes I know", "allegedly":"kinda probably", "new study": "Tumblr post",
	"rebuild":"avenge", "space":"spaaaace", "google glass":"Virtual Boy", "smartphone":"Pokédex",
	"video":"low-budget movie", "electric":"Atomic", "senator":"Elf-Lord", "car": "Cat",
	"election": "Eating contest", "Congress":"Clown-house", "Leader":"big BOI",
	"congressional leaders":"River spirits", "homeland security":"Homestar Runner", 
	"could not be reached for comment": "is guilty and everybody knows it", "reveals":"shows off", "unveils":"Flexes",
	"breaking news":"Yo! Check this out!", "plan":"last-minute idea",
	"fined":"grounded", "bitcoin":"Bitconeeeeeeeeeeect!!", "bit-coin":"Digital BLING", "big":"humongous", 
	"airline":"Flying-bus stations", "google":"Googol", "strongest":"MOST BUFFED",
	"deadly":"maybe dangerous", "announces":"yells out loud", "secrets":"Gossip", "healthy":"questionable",
	"unhealthy":"questionable", "tumor":"lil' ball'o flesh", "best":"not-so-bad", "stunning":"irrelevant", "lava": "earth-soup",
	"tips":"weird thoughts I had while on the restroom", "comedian":"Clown-Lord", "melania trump":"Trumpy's Waifu",
	"opinion:":"Something weird I thought while in the bathroom:",
	"captured":"trapped in a little box", "interview":"date", "student":"prisoner", "police":"Blue Bois",
	"italy":"Spaghettiland", "dies":"gets Game Over", "-year-old":"-year-young", "survives":"almost (but not) died",
	"trump":"Trumpy", "comments":"trash-talk", "free":"ultra low-cost", "helps":"gives a hand", "dog":"Doggo",
	"controversial":"Spicy", "teen":"old kid, very young adult", "radioactive":"nuclear", "package":"tic-tac container",
	"billionaire":"filthy-rich", "here's why":"pls click", "ambush":"ninja attack", "water":"dihidrogen monoxide",
	"boy":"dude", "girl":"dudette", "professor":"wise dude", "teacher":"wizard", "investigating":"Googling", 
	"food":"foodie", "father":"Old dude", "grandpa":"Gandalf", "alligator":"Godzilla",
	"confirmed":"maybe, possibly confirmed", "stalker":"creepy dude", "conflict":"battle", "volcano":"lava-shooting planet-pimple",
	"multiple":"a heck lot of", "pond":"big'ol, natural water bowl", "hundreds":"a lot", "school":"prison",
	"lawyer":"rookie Ace Attorney", "camera":"soul capture device", "drone":"levitating camera",
	"kim":"Kimmy", "watch":"check this out", "child":"very old baby, very young kid", "not a good idea":"a pretty bad idea",
	"":""}
